version: '3.8'
services:
  backend:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./angular-14-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
