services:
  angular-client:
    build:
      context: ./angular-14-client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-server

  spring-server:
    build:
      context: ./spring-boot-server
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
